package com.sachinbendigeri.spark.BGC.constants

object Constants {
  val PARAM_RUN_INSTANCE_TIME: String = "RunInstanceTime"
  val PARAM_TITLE_AKAS_TABLE: String = "BGC_TITLE_AKA_HiveTableName"
  val PARAM_TITLE_BASICS_TABLE: String = "BGC_TITLE_BASICS_HiveTableName"
  val PARAM_TITLE_PRINCIPLES_TABLE: String = "BGC_TITLE_PRINCIPLES_HiveTableName"
  val PARAM_TITLE_RATINGS_TABLE: String = "BGC_TITLE_RATINGS_HiveTableName"
  val PARAM_NAME_BASICS_TABLE: String = "BGC_NAME_BASICS_HiveTableName"

  val PARAM_TITLE_AKAS_FILEPATH: String = "BGC_TITLE_AKA_FilePath"
  val PARAM_TITLE_BASICS_FILEPATH: String = "BGC_TITLE_BASICS_FilePath"
  val PARAM_TITLE_PRINCIPLES_FILEPATH: String = "BGC_TITLE_PRINCIPLES_FilePath"
  val PARAM_TITLE_RATINGS_FILEPATH: String = "BGC_TITLE_RATINGS_FilePath"
  val PARAM_NAME_BASICS_FILEPATH: String = "BGC_NAME_BASICS_FilePath"
  
  val PARAM_BGC_TOP20MOVIES_TABLE: String = "BGC_TOP20MOVIES_HiveTableName"
  val PARAM_BGC_TOP20MOVIES_PRICNCIPLES_TABLE: String = "BGC_TOP20MOVIES_PRINCIPLES_HiveTableName"
  val PARAM_BGC_TOP20MOVIES_AKATITLES_TABLE: String = "BGC_TOP20MOVIES_AKATITLES_HiveTableName" 
}